---
groups:
- name: cf-deployment
  jobs:
  - delete-deployment-fresh
  - update-releases
  - deploy-releases
  - acceptance-tests
  - bless-manifest
- name: infrastructure
  jobs:
  - setup-infrastructure-fresh
  - destroy-infrastructure-fresh
  - create-bosh-director-fresh
  - destroy-bosh-director-fresh
  - setup-infrastructure
  - destroy-infrastructure
  - verify-nameserver-has-record
  - run-bosh-cleanup

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: cf-gcp-infrastructure
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/cf-gcp-infrastructure
- name: luna-terraform
  type: terraform
  source:
    storage:
      bucket: runtimeci-tfstate
      bucket_path: cf-deployment/
      region_name: us-west-1
      access_key_id: {{luna_terraform_s3_access_key_id}}
      secret_access_key: {{luna_terraform_s3_secret_key}}
    terraform_source: github.com/cloudfoundry-incubator/cf-gcp-infrastructure
    vars:
      project: {{luna_gcp_project}}
      env_name: luna
      region: us-central1
      zones: [us-central1-a, us-central1-b, us-central1-c]
      dns_suffix: cf-app.com
      ssl_cert: {{luna_cf_ssl_cert}}
      ssl_cert_private_key: {{luna_cf_ssl_cert_private_key}}
      service_account_key: {{gcp_service_account_json}}
- name: luna-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/luna-env.git
    private_key: {{luna_env_private_key}}
- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 3:30 -0700
    interval: 168h
- name: daily
  type: time
  source:
    start: 3:00 -0700
    stop: 3:30 -0700
    interval: 24h
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: hermione-env-infrastructure
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hermione-env.git
    private_key: {{hermione_env_private_key}}
    paths:
    - bbl-infrastructure/*
- name: hermione-env-properties
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hermione-env.git
    private_key: {{hermione_env_private_key}}
    paths:
    - deployment-env-vars.yml
    - integration_config_template.json
- name: hermione-env-integration-config
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hermione-env.git
    private_key: {{hermione_env_private_key}}
    paths:
    - integration_config.json
- name: cf-deployment-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: {{cf_deployment_private_key}}
- name: cf-deployment-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: {{cf_deployment_private_key}}
- name: capi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/capi-release
- name: nats-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/nats-release
- name: routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release
- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release
- name: loggregator-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/loggregator
- name: cf-mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: uaa-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release
- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release
- name: binary-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/binary-buildpack-release
- name: dotnet-core-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/dotnet-core-buildpack-release
- name: go-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/go-buildpack-release
- name: java-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/java-buildpack-release
- name: java-offline-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/java-offline-buildpack-release
- name: nodejs-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/nodejs-buildpack-release
- name: php-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/php-buildpack-release
- name: python-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/python-buildpack-release
- name: ruby-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/ruby-buildpack-release
- name: staticfile-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/staticfile-buildpack-release
- name: cflinuxfs2-rootfs-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

jobs:
- name: setup-infrastructure-fresh
  serial_groups: [setup-deploy-and-test-fresh]
  plan:
  - put: luna-terraform
    params:
      env_name: luna
      delete_on_failure: true

- name: destroy-infrastructure-fresh
  serial_groups: [setup-deploy-and-test-fresh]
  plan:
  - put: luna-terraform
    params:
      env_name: luna
      action: destroy
    get_params:
      action: destroy

- name: delete-deployment-fresh
  public: true
  serial_groups: [nats-deploy]
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: runtime-ci
      - get: luna-env
    - task: extract-director-creds-from-terraform-env
      file: runtime-ci/scripts/ci/extract-director-creds-from-terraform-env/task.yml
      input_mapping:
        env-repo: luna-env
    - task: delete-deployment-cf
      input_mapping:
        env-repo: luna-env
      file: runtime-ci/scripts/ci/delete-deployment-bosh-2-0/task.yml
      params:
        DEPLOYMENT_NAME: cf

- name: create-bosh-director-fresh
  serial_groups: [setup-deploy-and-test-fresh]
  plan:
  - get: runtime-ci
  - get: luna-env
  - get: cf-gcp-infrastructure
  - get: luna-terraform
  - task: create-gcp-bosh-director
    file: runtime-ci/scripts/ci/create-gcp-bosh-director/task.yml
    input_mapping:
      env-repo: luna-env
      terraform: luna-terraform
    params:
      NATS_PASSWORD: {{luna_nats_password}}
      MBUS_PASSWORD: {{luna_mbus_password}}
      HM_PASSWORD: {{luna_hm_password}}
      BLOBSTORE_AGENT_PASSWORD: {{luna_blobstore_agent_password}}
      BLOBSTORE_DIRECTOR_PASSWORD: {{luna_blobstore_director_password}}
      POSTGRES_PASSWORD: {{luna_postgres_password}}

- name: delete-deployment
  public: true
  serial_groups: [setup-deploy-and-test-fresh]
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: runtime-ci
        passed: [ delete-deployment ]
      - get: luna-env
    - task: extract-director-creds-from-terraform-env
      file: runtime-ci/scripts/ci/extract-director-creds-from-terraform-env/task.yml
      input_mapping:
        env-repo: luna-env
    - task: delete-deployment-cf
      input_mapping:
        env-repo: luna-env
      file: runtime-ci/scripts/ci/delete-deployment-bosh-2-0/task.yml
      params:
        DEPLOYMENT_NAME: cf

- name: deploy-releases
  serial: true
  serial_groups: [setup-deploy-and-test-fresh]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-develop
    - get: luna-env
      passed: [ delete-deployment ]
  - task: extract-director-creds-from-terraform-env
    file: runtime-ci/scripts/ci/extract-director-creds-from-terraform-env/task.yml
    input_mapping:
      env-repo: luna-env
  - task: bosh-deploy-cf
    file: runtime-ci/scripts/ci/bosh-deploy/task.yml
    input_mapping:
      manifest: cf-deployment-develop
      manifest-properties: luna-env
    params:
      TARGET_FILE:  target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      CA_CERT_FILE: ca-cert
      MANIFEST_FILE: cf-deployment.yml
      DEPLOYMENT_VARS_STORE: deployment-vars.yml
      SYSTEM_DOMAIN: luna.cf-app.com
      OPS_FILE: opsfiles/gcp.yml
    ensure:
      put: luna-env
      params:
        repository: updated-vars-store
        rebase: true

- name: destroy-bosh-director-fresh
  serial_groups: [setup-deploy-and-test]
  plan:
  - get: runtime-ci
  - get: luna-env
  - get: cf-gcp-infrastructure
  - task: destroy-gcp-bosh-director
    file: runtime-ci/scripts/ci/destroy-gcp-bosh-director/task.yml
    input_mapping:
      env-repo: luna-env
  - put: luna-env
    params:
      repository: updated-env-repo
  - put: luna-env
    params:
      repository: updated-env-repo

- name: destroy-infrastructure
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: hermione-env-infrastructure
    - get: runtime-ci
  - task: unbind-elb-from-r53
    file: runtime-ci/scripts/ci/unbind-elb-from-r53/task.yml
    input_mapping:
      env-repo: hermione-env-infrastructure
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      DOMAIN: hermione.cf-app.com
  - task: destroy-infrastructure
    file: runtime-ci/scripts/ci/destroy-infrastructure/task.yml
    input_mapping:
      env-repo: hermione-env-infrastructure
  - put: hermione-env-infrastructure
    params:
      repository: updated-env-repo

- name: setup-infrastructure
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: hermione-env-infrastructure
    - get: runtime-ci
  - task: setup-infrastructure
    file: runtime-ci/scripts/ci/setup-infrastructure/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      BBL_LB_CERT: {{hermione_lbs_ssl_cert}}
      BBL_LB_KEY: {{hermione_lbs_ssl_signing_key}}
    input_mapping:
      env-repo: hermione-env-infrastructure
  - put: hermione-env-infrastructure
    params:
      repository: updated-env-repo
  - task: bind-elb-to-r53
    file: runtime-ci/scripts/ci/bind-elb-to-r53/task.yml
    input_mapping:
      env-repo: updated-env-repo
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      DOMAIN: hermione.cf-app.com

- name: update-releases
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: hermione-env-infrastructure
    - get: cf-deployment-develop
    - get: hermione-env-properties
    - get: stemcell
      trigger: true
      params:
        tarball: false
    - get: capi-release
      trigger: true
      params:
        tarball: false
    - get: nats-release
      trigger: true
      params:
        tarball: false
    - get: routing-release
      trigger: true
      params:
        tarball: false
    - get: consul-release
      trigger: true
      params:
        tarball: false
    - get: etcd-release
      trigger: true
      params:
        tarball: false
    - get: diego-release
      trigger: true
      params:
        tarball: false
    - get: loggregator-release
      trigger: true
      params:
        tarball: false
    - get: cf-mysql-release
      trigger: true
      params:
        tarball: false
    - get: uaa-release
      trigger: true
      params:
        tarball: false
    - get: garden-runc-release
      trigger: true
      params:
        tarball: false
    - get: cflinuxfs2-rootfs-release
      trigger: true
      params:
        tarball: false
    - get: binary-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: dotnet-core-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: go-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: java-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: java-offline-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: nodejs-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: php-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: python-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: ruby-buildpack-release
      trigger: true
      params:
        tarball: false
    - get: staticfile-buildpack-release
      trigger: true
      params:
        tarball: false
  - task: extract-director-creds-from-bbl
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
    input_mapping:
      env-repo: hermione-env-infrastructure
  - task: create-binaries-manifest-section
    file: runtime-ci/scripts/ci/create-binaries-manifest-section/task.yml
    input_mapping:
      deployment-configuration: cf-deployment-develop
  - task: commit-generated-manifest
    file: runtime-ci/scripts/ci/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      manifest: deployment-manifest
    params:
      MANIFEST_NAME: cf-deployment.yml
      MANIFEST_DESTINATION: cf-deployment.yml
      COMMIT_MESSAGE: 'Update releases'
  - put: cf-deployment-develop
    params:
      repository: updated-repo
  - task: bosh-upload-stemcell
    file: runtime-ci/scripts/ci/bosh-upload-stemcell/task.yml
    input_mapping:
      cf-deployment: updated-repo
    params:
      INFRASTRUCTURE: aws

- name: deploy-releases
  public: true
  serial: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-develop
      trigger: true
    - get: hermione-env-properties
      trigger: true
    - get: hermione-env-infrastructure
  - task: extract-director-creds-from-bbl
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
    input_mapping:
      env-repo: hermione-env-infrastructure
  - task: bosh-deploy-cf
    file: runtime-ci/scripts/ci/bosh-deploy/task.yml
    input_mapping:
      manifest: cf-deployment-develop
      manifest-properties: hermione-env-properties
    params:
      TARGET_FILE:  target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      CA_CERT_FILE: ca-cert
      MANIFEST_FILE: cf-deployment.yml
      DEPLOYMENT_VARS_STORE: deployment-env-vars.yml
      SYSTEM_DOMAIN: hermione.cf-app.com
      OPS_FILE: opsfiles/change-logging-port-for-aws-elb.yml
    ensure:
      put: hermione-env-infrastructure
      params:
        repository: updated-vars-store
        rebase: true

- name: acceptance-tests
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: runtime-ci
      - get: cf-acceptance-tests
      - get: hermione-env-properties
        trigger: true
        passed: [ deploy-releases ]
      - get: cf-deployment-develop
        trigger: true
        passed: [ deploy-releases ]
      - get: hermione-env-integration-config
    - task: write-target-file-api
      file: runtime-ci/scripts/ci/write-target-file/task.yml
      params:
        TARGET: api.hermione.cf-app.com
    - task: enable-docker-diego
      file: runtime-ci/scripts/ci/cfd-enable-docker-diego/task.yml
      params:
        VARS_STORE_PATH: deployment-env-vars.yml
        SYSTEM_DOMAIN: hermione.cf-app.com
      input_mapping:
        cf-deployment: cf-deployment-develop
        env-repo: hermione-env-integration-config
    - task: run-cats
      input_mapping:
      - integration-config: hermione-env-integration-config
      file: runtime-ci/scripts/ci/run-cats/task.yml

- name: bless-manifest
  public: true
  serial: true
  build_logs_to_retain: 100
  plan:
    - do:
      - aggregate:
        - get: runtime-ci
        - get: hermione-env-properties
          trigger: true
          passed: [ acceptance-tests ]
        - get: cf-deployment-develop
          trigger: true
          passed: [ acceptance-tests ]
        - get: cf-deployment-master
    - put: cf-deployment-master
      params:
        repository: cf-deployment-develop

- name: verify-nameserver-has-record
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - get: runtime-ci
    - get: weekly
      trigger: true
    - task: verify-nameserver-has-record
      file: runtime-ci/scripts/ci/verify-nameserver-has-record/task.yml
      params:
        AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
        DOMAIN: hermione.cf-app.com

- name: run-bosh-cleanup
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: runtime-ci
      - get: hermione-env-infrastructure
      - get: daily
        trigger: true
    - task: extract-director-creds-from-bbl
      file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
      params:
        STATE_DIR_PATH: bbl-infrastructure
      input_mapping:
        env-repo: hermione-env-infrastructure
    - task: run-bosh-cleanup
      privileged: true
      file: runtime-ci/scripts/ci/run-bosh-cleanup/task.yml
